### ISSUE TITLE
Overwriting of the user object, loss of access token and refresh token in session.

### ISSUE THREAD

**Issue by lpkobamn** [directus-labs/guest-authoring#100]
### What is your idea?

      https://docs.directus.io/blog/directus-auth-nextauth.html#creating-the-login-api
      session.user.access Token = token.access Token;
      session.user.refresh Token = token.refresh Token;
      session.user = token.user; // this rewrites previous

### What are the key takeaways from your post?

Overwriting of the user object, loss of access token and refresh token in session.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

GEO

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thanks for the report!

**Comment by phazonoverload** [comment]
(not yet completed - but tracked elsewhere)
