### ISSUE TITLE
Contact Form [HTML Only] with Custom Directus Extension and Autoresponder using Directus Automate

### ISSUE THREAD

**Issue by Marktawa** [directus-labs/guest-authoring#105]
### What is your idea?

This project provides a fallback solution to scenarios where JavaScript is disabled by a client on the frontend of a web app. In the absence of client-side JavaScript, form submissions can still be handled by a custom Directus endpoint extension which will receive the submitted form data and update the collection.

A bonus feature of this is to use Directus Automate to automatically send email notifications to the Directus admin and the user.

### What are the key takeaways from your post?

Readers will learn:
- How to create a custom extension (Endpoint Extension) for use in a Directus project
- How to set up Directus Automate for automated email notifications (Flows and Triggers)

### What type of post is this?

Extension-Building Guide

### Country of residence

Zambia

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
