### ISSUE TITLE
Getting Started With Directus and Docusaurus 

### ISSUE THREAD

**Issue by Marktawa** [directus-labs/guest-authoring#108]
### What is your idea?

Docusaurus is a React based static site generator, popular for building blogs and documentation sites. This tutorial is about building a website using Directus and Docusaurus. It will follow the framework guides in the docs.

### What are the key takeaways from your post?

Readers will learn:
- How to create a website using Docusaurus 
- How to set up the Directus SDK in a Docusaurus project
- How to set up a Directus project (Collections, Fields, Items, Access Control) API.
- How to fetch and render data (pages, posts, images, etc) using the Directus SDK in Docusaurus 

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Zambia 

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
