### ISSUE TITLE
Build a Survey app with Analytics

### ISSUE THREAD

**Issue by Marktawa** [directus-labs/guest-authoring#109]
### What is your idea?

Build a survey form web app using Sveltekit as the frontend framework and Directus as the headless CMS. In addition, build a panel to analyze survey results in the Directus Admin using Directus Insights.

### What are the key takeaways from your post?

By the end of this tutorial, participants will be able to:

* Create user interfaces for building and taking surveys using Sveltekit 
* Integrate Directus using the Directus SDK in the survey app for data storage and retrieval.
* Implement functionalities to submit survey responses and store them in a Directus project 
* Use Directus Insights as an Analytics tool to visualize survey data in real time.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Zambia 

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by Marktawa** [comment]
No, I hadn't thought about automatic generation of surveys. I can however adjust my proposal to include automatic generation of surveys using Directus.

**Comment by phazonoverload** [comment]
I think that would be more interesting - basically a frontend form generator based on a schema. Right now, it's basically just a hardcoded frontend, a POST request, and an insights dashboard which I think is less interesting. What do you think?

**Comment by Marktawa** [comment]
This works for me as well.

Here's a rough outline:
- Directus Panel to generate a survey (collection and fields) automatically
- Build frontend to display Survey
- Insights dashboard to visualize collected data

**Comment by phazonoverload** [comment]
Very nice - the frontend and dashboard can remain minimal - a panel extension to generate the collection/fields would be the main part and sounds great. 

Based on the agreed scope we can pay $500 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our May content schedule. The first draft is due on April 2 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by Marktawa** [comment]
Awesome. I'm ok with the scope and can commit to the suggested deadline. I'm ready to get started, so you can approve the issue.

**Comment by phazonoverload** [comment]
Any update on this @Marktawa?

**Comment by Marktawa** [comment]
I am still working on this one. I'll be sure to ping once I'm done.

**Comment by phazonoverload** [comment]
The deadline for a first draft was April 2 so I'm gonna need a more concrete update please

**Comment by phazonoverload** [comment]
@Marktawa I'll need a draft by the end of Monday or I'm afraid this post will not be accepted or posted as part of this program.

**Comment by Marktawa** [comment]
Hey Kevin

I am still working on the draft. I will need a little more time to complete it. Can you please extend the deadline for the initial draft to Monday 22nd April?

**Comment by phazonoverload** [comment]
We can do this if you are able to commit to responding to reviews within 48 hours.
