### ISSUE TITLE
Getting Started With Directus And Flask

### ISSUE THREAD

**Issue by guilhermesdev** [directus-labs/guest-authoring#111]
### What is your idea?

The tutorial will show readers how to create an application with Flask and Directus, following the same structure from the other getting started guides.

This could be useful for Python teams who want an admin UI to manage their data internally but don't want to build it from scratch or use the available Flask alternatives, which are not so flexible and do not have as good docs as Directus.

### What are the key takeaways from your post?

- How to set up a Flask project
- How to use Directs via REST API
- How to create collections in a Directus project
- How to render directus data using templates

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Brazil

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This has to follow the standard format for our framework getting started guides:

- Initialize project
- Create a helper/lib/plugin (unsure of Angular-specific terminology) for Directus SDK
- Globals
- Dynamic Pages
- Blog listing
- Blog single
- Nav

Here's an example: https://docs.directus.io/guides/headless-cms/build-static-website/nuxt-3

Based on the agreed scope we can pay $250 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our May content schedule. The first draft is due on April 2 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by guilhermesdev** [comment]
Hi, Kevin, thanks for the response!

I'm happy to commit to the deadline and will start working on it as soon as possible.
