### ISSUE TITLE
Build an E-commerce Website With Directus and Next.js

### ISSUE THREAD

**Issue by codejagaban** [directus-labs/guest-authoring#115]
### What is your idea?

In this article, I'll go over how developers can build an e-commerce website with Directus and Next.js.

Features of the application include:

- Listing available items on the Frontend
- Using Directus for managing the product inventory  and users
- Search feature to search products from Directus
- Receiving payment with Stripe or other payment providers
- After payment confirmation, perform a request to Directus to mark the product as paid

### What are the key takeaways from your post?

Key takeaways from the article include:

- Learning how to use advanced filter parameters in Directus
- Implement relational data models in Directus and search functionality in the Frontend application

At the end of the article, readers will have an overview of how they can easily set up an e-commerce website with Directus and receive payments in their applications.

### What type of post is this?

Full Project Build with Directus

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Seeing that this is quite similar to the hotel booking system post, but with small changes and a different theme, we can pay $350 for this post. Publish in June, May 1 deadline for first draft. How's that sound?

**Comment by codejagaban** [comment]
Do you think the features I initially mentioned are enough or things like cart functionality and auth?

**Comment by phazonoverload** [comment]
I think your original scope was totally fine. Is the timeline workable?

**Comment by codejagaban** [comment]
Okay great, the timeline works for me

**Comment by phazonoverload** [comment]
Is there an update? The draft deadline has passed

**Comment by phazonoverload** [comment]
Hey @codejagaban please can you provide an update on this? If we don't get one by the end of Wednesday we will assume you're no longer able or interested in doing it.

**Comment by codejagaban** [comment]
Hi @phazonoverload, sincere apologies for the delay. I had a failing health issue I had to deal with over the past few weeks. I'll submit the draft by the end of today
