### ISSUE TITLE
Directus and IoT: Sensor Data with an ESP32

### ISSUE THREAD

**Issue by vicradon** [directus-labs/guest-authoring#119]
### What is your idea?

This is an article that gets users started with using Directus for IoT projects. It’s a simple project that demonstrates how to collect and visualize temperature and humidity data from a DHT22 temperature and humidity sensor and send this data to Directus through an ESP32. An ESP32 is a board that allows IoT developers and hobbyists to work with sensors and controllers with built-in Wifi support. This Wifi support allows the board to connect to the internet and send data to destinations such as Directus by making HTTP calls. Below is a quick overview of the major sections of the article:

1. It begins by highlighting the necessity of collecting and visualizing temperature and humidity data in various settings, including industrial and home environments.
2. Next, it illustrates both physical and simulated circuit configurations to aid readers in implementing the project using either physical components or the Wowki IoT simulator.
3. The setup process for Directus is then outlined, offering guidance on configuring it either through Directus Cloud or a self-hosted setup.
4. Instructions are provided for creating a collection named "temperature_and_humidity," designed to store temperature and humidity data with four essential fields: id, temperature, humidity, and date_created.
5. A demonstration follows on how to send data to this collection using the Directus REST API.
6. Subsequently, readers are acquainted with making HTTP calls from an ESP32 using embedded C++ scripting.
7. The article proceeds to showcase a demo of the HTTP POST request responsible for sending data to the "temperature_and_humidity" collection from the ESP32 script.
8. The final step involves visualizing the accumulated temperature and humidity data using Directus Dashboards.
9. Concluding the article, a discussion is presented, reflecting on the completed tasks and potential enhancements, such as incorporating a board_id field to identify the source board for each record within the collection.

### What are the key takeaways from your post?

1. How to store data from an IoT system to the cloud with the aid of Directus
2. How to use Directus dashboards to easily visualize data from a database
3. How to use the Directus API to make POST requests
4. How to effectively utilize role permissions and access tokens in a Directus-powered project

### What type of post is this?

Full Project Build with Directus

### Country of residence

 Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Are you happy to frame this as `Directus and IoT: Sensor Data with an ESP32`? I think the topic you've submitted is interesting, but if we generalize a bit (this is about IoT generally with this fairly straightforward example to start) I think it would have more appeal.

**Comment by vicradon** [comment]
Hi @phazonoverload 
I think your topic suggestion is still reasonable enough for the proposed outline. What do you think about the outline?

**Comment by phazonoverload** [comment]
Yup all good! It's just narrative, not actual technical changes. 
Based on the agreed scope we can pay $500 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our June content schedule. The first draft is due on May 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by vicradon** [comment]
Thank you @phazonoverload 
Can the post be included in the May schedule instead? I will submit the first draft on Monday, the 15th of April.

**Comment by vicradon** [comment]
Ah, I see. I thought the payment was based on the publication month. I'll try my best to complete it before April runs out. Thank you!

**Comment by vicradon** [comment]
Hi @phazonoverload 
I submitted the first draft a few days back. Could you please take a look at it?

**Comment by phazonoverload** [comment]
No need to bump - I've seen and have scheduled in time to review it.
