### ISSUE TITLE
Deploy Directus to Civo cloud Kubernetes Cluster

### ISSUE THREAD

**Issue by davidmbochi** [directus-labs/guest-authoring#121]
### What is your idea?

Civo is one of the cheapest cloud providers compared to AWS and Azure. As a result, the likelihood that most startups might prefer hosting with Civo is very high. In this tutorial, the reader will learn how to deploy Directus to the Civo Kubernetes cluster. 

### What are the key takeaways from your post?

- How to deploy a self-hosted instance of Directus to the Civo cloud
- How to connect to PostgreSQL database
- How to connect the Civo object store for storing files

### What type of post is this?

Self-Hosting Guide

### Country of residence

Kenya

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We haven't had much demand for this cloud hosting provider in the past. Please feel free to submit additional ideas in future.
