### ISSUE TITLE
Build a blog using Directus Headless CMS and Next.js 14

### ISSUE THREAD

**Issue by emmanuelhashy** [directus-labs/guest-authoring#123]
### What is your idea?

This article will give you a hands-on approach to exploring the capabilities of the Directus Headless CMS and creating a custom API from scratch.

It will help JavaScript developers put their knowledge to work by guiding them through building powerful backend APIs. You’ll see how to effortlessly create content structures that can be customized according to your needs, and gain insights into how to write, edit, and manage your content seamlessly with Directus Headless CMS. 

You'll learn how to integrate the backend APIs with server-rendered React application built with Next.js 14

### What are the key takeaways from your post?

Readers will learn:
1. How to create content structures that can be customized according to their needs
2. How to build powerful backend APIs
3.  How to write, edit, and manage content seamlessly with Directus Headless CMS

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We already have this in our docs :)
