### ISSUE TITLE
Implement Directus Auth in Next.js 14

### ISSUE THREAD

**Issue by emmanuelhashy** [directus-labs/guest-authoring#124]
### What is your idea?

This article will give you a hands-on approach to handling user authentication and authorization with Directus and Next.js 14

It will help JavaScript developers put their knowledge to work by guiding them through implementing user authentication and authorization with Directus. You’ll see how to implement user authentication and authorization with Directus Headless CMS effortlessly.

You'll learn how to integrate the backend APIs with server-rendered React application built with Next.js 14

### What are the key takeaways from your post?

Readers will learn:

How to implement user authentication
How to implement user authorization middleware
How to integrate backend APIs with server-rendered React application built with Next.js 14

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by Malaccoda** [comment]
The Tutorial is great. But you forgot one thing at the beginning. That the Public can create a new account you need to assign the corresponding permissions. I.e. first_name, last_name, email, password AND role (the last one didn't show up without expanding, so it got me a real headache) 
![directus-create-user](https://github.com/directus-labs/guest-authoring/assets/87227954/2f5210ba-392e-4f32-a76c-e80cf8f9b9e2)

**Comment by emmanuelhashy** [comment]
Can you please provide more insight on how we can get started with the pitch?

**Comment by phazonoverload** [comment]
> We work through new ideas every few weeks as we put together our content schedule. This means you may not get an immediate response as to whether your idea has been accepted, or any follow-up questions we have to clarify your idea.

**Comment by phazonoverload** [comment]
Thanks for the enthusiasm everyone. We currently only work with one author on a given idea, including the whole review process, so I'll be picking this up with Emmanuel only. 

---

So hello @emmanuelhashy - this is a post we'd love for you to write. I have given a lot of thought to auth tutorials and I want to propose the following format to keep them consistent: 

1. Set up a `posts` collection - with a user_created, date_created, title, and content field.
2. Set up a new `Users` role with the following permissions:
  - Read all
  - Create all
  - Update and delete where `$CURRENT_USER.id == user_created.id`
3. Allow public create on `directus_users` where:
  - Limited to only providing email and password
  - Field preset where role = new-role-id
4. Next.js-specific portion:
  - registration, login, refresh token handling
  - List all posts
  - Create post
  - Edit/delete post

How's this sound?

**Comment by emmanuelhashy** [comment]
@phazonoverload This sounds great!

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $500 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our May content schedule. The first draft is due on May 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by emmanuelhashy** [comment]
@phazonoverload I'm interested and happy to commit to the deadline.

**Comment by clifflee404** [comment]
> The Tutorial is great. But you forgot one thing at the beginning. That the Public can create a new account you need to assign the corresponding permissions. I.e. first_name, last_name, email, password AND role (the last one didn't show up without expanding, so it got me a real headache) ![directus-create-user](https://private-user-images.githubusercontent.com/87227954/318159353-2f5210ba-392e-4f32-a76c-e80cf8f9b9e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTQ1NzAsIm5iZiI6MTcxNDYxNDI3MCwicGF0aCI6Ii84NzIyNzk1NC8zMTgxNTkzNTMtMmY1MjEwYmEtMzkyZS00ZjMyLWE3NmMtZTgwY2Y4ZjliOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDAxNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZDJhYWNlZDU0NzE4NTI3N2FjMWJlNzgzNWQ3OTRlNzk4MzJlZDUyODUyNmNiMDhjNDg2YmU4MTYwY2JlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hos3wowdpJgZL5i7ab5BaAd2fzDIZ3k0hASp3sRNNms)

@Malaccoda  Thank you so much. I just encountered this problem while following the [tutorial](https://docs.directus.io/blog/directus-auth-nextauth.html). If the Field Validation part is not configured, or if 'Role' is missing from the configuration, the following error will occur when registering a user. I have looked for many solutions but none have worked. Thank you for your kind reminder.
<img width="480" alt="image" src="https://github.com/directus-labs/guest-authoring/assets/131660075/c81c94d1-2787-4892-a313-1f1adc40328b">

**Comment by clean-logic** [comment]
Directus is a beautiful! But you guys got screwed out of $500. This article is written with outdated NextJS version in mind, not 14 where SSR is the default. And as such it is pretty useless. Also, that is not how you "protect the routes" in NextJS 14. There is middleware for that.

**Comment by emmanuelhashy** [comment]
Thank you for your feedback @codestrong . I want to clarify that the article was written using NextJS 14, and I initially used middleware for route protection. I made sure to incorporate the suggestions from the initial draft review.
