### ISSUE TITLE
Directus self-hosted instance on aws lightsail Ubuntu 22.04 with cloudron server managment tool

### ISSUE THREAD

**Issue by alexmazaltov** [directus-labs/guest-authoring#126]
### What is your idea?

I want to share my experience of how I was able to create an AWS Lightsail Ubuntu 22.04 instance (22.04.1-Ubuntu SMP Wed Mar 13 18:54:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)
The delivery path of custom extensions in that case is complicated and not obvious and needs to be clarified.

### What are the key takeaways from your post?

1. Creating AWS Lightsail instance that fits with cloudron requirements.
2. Bind static IP address to be pointed in my domain management, as well creating A record for new subdomain to be specified during setting up cloudron server (e.g.: cloud.alefinvest.xyz)
3. Perform updates in aws lightsail instances before running up cloudron-setup shell script.
4. Setting up A record to finalist cloudron server management (my.cloud.alefinvest)
5. Setting up A record for new app(directus 10.10.5) installation directus.cloud.alefinvest.xyz
6. Delivery custom extension via filemanager UI inside installed directus app.
7. TODO: Performing steps following [README.md](https://github.com/alefinvest/directus-extension-stripe/blob/main/README.md) in example folder of custom directus-extension-stripe

### What type of post is this?

Self-Hosting Guide

### Country of residence

Ukraine, US

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by alexmazaltov** [comment]
Is Ukrainian location acceptable for contributions in dev blog?

**Comment by phazonoverload** [comment]
Yes indeed. As long as there's no US trade embargo we are open to authors from all over the world 😄 There are some regions where paying is harder, which is why we ask upfront. As far as I remember, Ukraine has never been an issue in the past. 

Now, I'm wondering how generic we can go with this post in terms of extension delivery for self-hosted projects. Any thoughts?

**Comment by alexmazaltov** [comment]
I think we can cover the deployment via cloudron the `directus backend app` and `nextjs frontend app`` to fetch data from directus app via API.

Here my repo that prove possibility to do so: https://github.com/alexmazaltov/nextjs-app-for-directus-vai-cloudron

**Comment by phazonoverload** [comment]
Hey @alexmazaltov and apologies for the delay. On further review, this seems like a very niche setup for specific vendors, so it isn't the right fit for this program.
