### ISSUE TITLE
Building a simple online book club and renting business with Directus

### ISSUE THREAD

**Issue by isocroft** [directus-labs/guest-authoring#128]
## Idea

>The idea here is to use Directus as a Headless CMS to catalog books of various genres and topics and use Directus to power  a frontend dashboard for a simple online book club and renting business.

This business runs on ad revenue from Google AdSense and will have gig economy (last-mile) dispatch riders deliver the rented hard-cover books to the home of users. At the point of delivery, these dispatch riders will proceed to collect a surcharge with the Point-Of-Sale (POS) machines that they carry which is simply an incentive to return the book (after reading it) and on time.

Every user has 48 hrs after a rent call (which is specific vocabulary for indicating to rent a book) to cancel it if not they stand a chance of being barred from rent calling for a month.

As soon as the book is physically returned by the user to a designated drop-off points nearby, the surcharge is refunded fully (only if they returned the book back on time and not mutilated)

The business will have the following features:
- Directus Users (Signup + Registrations)
- Directus Auth (Login/Logout)
- Account Retrieval (Forget Password)
- Book Review Posts (where other users can join you to review a book in the comment section)
- Trends (Top Titles - book that most people are reading or have read)
- Recently Added Section (Listing recently added book titles)
- Available For Rent Section (Listing book available for rent)
- Recommended Books Tab (Recommended books for people who have read the books you have also read or are reading)
- Directus Activities for activities you perform on the app
- Directus Shares to Social Media for the books your are currently reading based on a rent call from the app
- Directus Items & Collections for the books added to the total inventory of books and book review posts
- Directus Notifications from other users who are (by default) subscribed to all Book Review posts
- Directus Wehooks for Book Review Posts creation and update only 

These features will be built out in a _**Github repo**_ and the codebase explained in sections in the article. The article will start with an introduction of what **Directus** is and what it can do. Then followed by a simple table of contents and then the walkthrough of the codebase and specifically how the **Directus** API reference was used to build it all out.

## Takeaways

1. Readers will be able to create and build fully functional projects (or even businesses) with Directus
2. Readers will learn how to make use of the API references features in several simple steps

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Hey. This is a thought through submission with a complex project, but I think there's too much going on to be useful from an educational standpoint. There are a few discreet parts in this that would make good pieces of content in isolation:

1. Managing dispatch riders, providing gigs, accepting, giving details, completion, etc.
2. Managing rentals (and availability blocking).
3. POS integration
4. Lots of social network stuff - reviews, trends, shares, etc.

I would encourage you to open a new submission for one of these. However, we don't accept multi-part series, so I would expect to see a complete end-to-end generic example being submitted.

**Comment by isocroft** [comment]
Hello @phazonoverload , I would like to understand better what you mean by:

> so I would expect to see a complete end-to-end generic example being submitted

Do you mean i should write some code or just give a descriptive example of the content in isolation ?
