### ISSUE TITLE
Passwordless authentication with Directus Flows

### ISSUE THREAD

**Issue by krazyjakee** [directus-labs/guest-authoring#129]
### What is your idea?

Using the Plivo Verify API, the client can send a phone number, receive an OTP code and then create a valid session for the directus user.

### What are the key takeaways from your post?

Beyond passwordless mobile authentication, email and magic link could also work the same way.

### What type of post is this?

Tips, Tricks, or Best Practice

### Country of residence

UK

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thanks for filling in the form following our call. Based on the agreed scope we can pay $500 for this post.

This post will be included as part of our June content schedule. The first draft is due on May 6 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by krazyjakee** [comment]
Happy to commit to the deadline
