### ISSUE TITLE
How to Create and Use SMS and Email Services in Directus

### ISSUE THREAD

**Issue by Claradev32** [directus-labs/guest-authoring#132]
### What is your idea?

This guide entails the setup and configuration process for integrating SMS and email services into Directus projects. It covers aspects such as selecting service providers, obtaining necessary API or SMTP credentials, configuring services within Directus, designing message templates, and integrating these services into workflows through actions and triggers.

### What are the key takeaways from your post?

The key takeaways are as follows:

Setting Up Directus
- Installation and setup
- Creating a project and configuring settings
- Understanding Directus services

- Configuring SMS Service
    - Choosing an SMS service provider
    - Obtaining API credentials
    - Configuring SMS service in Directus

- Implementing Email Service
   - Selecting an email service provider
   - Obtaining SMTP credentials
   - Configuring email service in Directus
   
- Creating Templates
   - Designing SMS templates
   - Designing email templates
   - Storing templates in Directus

- Integrating Services with Directus
   -  Setting up SMS actions and triggers
   - Setting up email actions and triggers
   - Testing communication services

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
