### ISSUE TITLE
Building a Blog with Next.js and Directus: A Step-by-Step Guide

### ISSUE THREAD

**Issue by Eunit99** [directus-labs/guest-authoring#136]
### What is your idea?

In this article, I will walk the reader through a step-by-step guide to building a dynamic blog using Next.js and Directus. The reader will learn how to set up a Next.js blog and connect it to their Directus instance.

The reader will also learn how to build various functionalities for their blog like how to manage global website metadata, create dynamic pages, fetch blog posts from the Directus database, sorting, and display content with linked authors and featured images.

### What are the key takeaways from your post?

* Headless CMS with Directus
* How to set up a NextJS project to fetch data from a remote backend.
* How to create data collections in a Directus project.
* How to set up Directus as a backend using a REST API.
* How to serve and build a NextJS project.
* API Fetching and Data Management

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
