### ISSUE TITLE
Getting Started with Directus and Android with Kotlin

### ISSUE THREAD

**Issue by icode247** [directus-labs/guest-authoring#142]
### What is your idea?

This comprehensive guide will take developers through the intricate process of building a cross-platform blog application using Kotlin and Directus. From setting up Directus APIs to handling data retrieval, manipulation, and synchronization across platforms, every aspect will be thoroughly explored. Moreover, it will delve into UI/UX design considerations, incorporating multimedia content, and implementing features such as real-time updates and user authentication. By following this guide, developers will gain a deep understanding of leveraging Kotlin and Directus to create a robust and user-friendly cross-platform blog application, equipped with seamless data management and engaging functionalities.

### What are the key takeaways from your post?

- Why use Kotlin?
- Why Directus rocks
- Benefits of Using Kotlin and Directus Together for Building a Blog App
- Building a Blog App with Kotlin and the Directus Blog Engine 
- Establishing the Directus Blog Engine
- Kotlin Integration with Directus
- Let’s get into building out our Blog App
- Concluding Remarks

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Hey! This topic isn't one we want to explore, but could I suggest a 'Getting Started with Directus and Android with Kotlin' post? Is that something you might be interested in?

**Comment by icode247** [comment]
Hi @phazonoverload 
Yes, I'm interested in working on a  'Getting Started with Directus and Android with Kotlin' post.

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $250 for this post and the accompanying repository which you can create in your account and we will fork.

This has to follow the standard format for our framework getting started guides:

1. Initialize project
2. Create a helper/lib/plugin (unsure of Kotlin-specific terminology) for Directus SDK
3. Globals
4. Dynamic Pages
5. Blog listing
6. Blog single
7. Nav

Here's an example: https://docs.directus.io/guides/headless-cms/build-static-website/nuxt-3

It needs to follow the format of our other getting started guides. 

This post will be included as part of our June content schedule. The first draft is due on June 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by icode247** [comment]
Hi @phazonoverload,
I can work with your recommended outline and I can commit to the deadline.

Thanks
