### ISSUE TITLE
Building a Scalable CRUD Image Gallery with Directus Files and Next.js

### ISSUE THREAD

**Issue by emmanuelbacf** [directus-labs/guest-authoring#143]
### What is your idea?

This article teaches the reader how to build a powerful image gallery application. It uses the combined features of Directus Files and Next.js.

Directus Files, a headless CMS with a Files Toolkit, handles image management like on-the-fly resizing and CDN integration.

Next.js, a performant React framework, offers features like the Image component for optimized image rendering.

The article guides the reader through the entire development process. They will learn to create reusable components to display single images and manage the overall gallery layout. I will walk the reader through implementing CRUD (Create, Read, Update, Delete) functionalities for images, allowing users to upload, edit, and delete them.

### What are the key takeaways from your post?

Through this article, readers will learn:

- How to build a scalable image gallery application that enables users to upload, view, edit, and delete images, all while leveraging Directus Files for efficient image management and Next.js for a performant and user-friendly experience.
- How to use Directus Files' features for image management, including on-the-fly resizing, compression, and CDN integration.
- Techniques for optimizing image delivery in a Next.js application using features like the Image component and caching strategies.

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
