### ISSUE TITLE
Build a Pet Adoption App Using Directus and Flutter.

### ISSUE THREAD

**Issue by oriohac** [directus-labs/guest-authoring#145]
### What is your idea?

The idea is to create a cross-platform application using Directus and Flutter, which its functionality will include authentication, which will be handled by the Directus authentication where users who want to put up their pet for adoption can easily put up such, and anyone who wants to adopt a pet can easily adopt one from the users who have put up their pets for adoption.

### What are the key takeaways from your post?

This article will teach readers:

- How to build a pet adoption app with Directus and Flutter. 
- Users creation.
- Implementation of user authentication with Directus on Flutter.
- Basic file operations.

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
