### ISSUE TITLE
Build a personal blog with Nuxt.js and Directus. 

### ISSUE THREAD

**Issue by y0ngdev** [directus-labs/guest-authoring#146]
### What is your idea?

We can't overstate the need for a personal blog as a developer, so I'll show readers how to create a personal blog that runs on Directus CMS in this tutorial.

### What are the key takeaways from your post?

This article will teach readers:

- How to manage content with a headless CMS
- How to host files with directus files toolkit

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by y0ngdev** [comment]
Is Nigeria an acceptable location for contributions to the directus blog?

**Comment by phazonoverload** [comment]
We have quite a few Nigerian guest authors, but already have this content in our docs.
