### ISSUE TITLE
Build a Directus Powered WebNote Keeper Chrome Extension

### ISSUE THREAD

**Issue by jaybharadia** [directus-labs/guest-authoring#150]
### What is your idea?

The idea is to create a Chrome extension called "WebNote Keeper" that allows users to save notes related to webpages they visit. The extension will leverage Directus as the backend CMS to store and manage these notes. When a user clicks the extension while browsing a webpage, it will automatically capture the URL of the current webpage and prompt the user to add a note. Users will be able to view, edit, and delete their notes directly from the extension's interface. The extension will integrate with Directus API for CRUD operations on notes. This project combines the use of Directus as a headless CMS and Chrome extension development skills to create a practical tool for users to organize their web research and thoughts.

### What are the key takeaways from your post?

- Directus Integration
- Chrome Extension Development
- Directus API Integration
- User Interface Design
- Transferrable Skills
- Practical Application

### What type of post is this?

Full Project Build with Directus

### Country of residence

India

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $350 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our June content schedule. The first draft is due on June 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by jaybharadia** [comment]
@phazonoverload 
Yes, i am happy to submit the project as per the deadline and expectations 👍

**Comment by jaybharadia** [comment]
@phazonoverload PR https://github.com/directus-labs/guest-authoring/pull/214
