### ISSUE TITLE
Implement Directus Auth in Flutter

### ISSUE THREAD

**Issue by oriohac** [directus-labs/guest-authoring#151]
### What is your idea?

This article will show users how to implement Directus auth on applications built with Flutter.

### What are the key takeaways from your post?

- Readers will get hands-on guide on how to set up Directus with Flutter.
- Readers will learn practical implementation of Directus Authentication and Authorization in Flutter Apps.
- Learn how to build Flutter Apps

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. While I'm interested in Auth x Framework posts, there's currently not enough demand for a Flutter variant. Please feel free to submit additional ideas in future.

**Comment by oriohac** [comment]
> Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. While I'm interested in Auth x Framework posts, there's currently not enough demand for a Flutter variant. Please feel free to submit additional ideas in future.

Thank you for your response, with this, do you mean one should not write anything relating to Flutter?

**Comment by oriohac** [comment]
When there's demand for the Flutter variant of Auth x Framework, can I go ahead to write?
