### ISSUE TITLE
Build a blog with SvelteKit and  Directus

### ISSUE THREAD

**Issue by xKachi** [directus-labs/guest-authoring#153]
### What is your idea?

This article will teach readers how to build a blog with SvelteKit(frontend/UI) and Directus(Storage and Authentication).

### What are the key takeaways from your post?

At the end of the article, the reader will be able to do the following:

- Create blog UI with Sveltekit
- Set up Directus with Directus Cloud
- Integrate Directus with SvelteKit
- Data storage and retrieval with Directus
- Authentication with Directus
- Implement app routing with SveltKit

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We already have this post
