### ISSUE TITLE
Building a Trello Clone with Remix and Directus

### ISSUE THREAD

**Issue by wisdomekpotu** [directus-labs/guest-authoring#154]
### What is your idea?

The idea is to show how to build a Multi-user Trello Clone using Directus as the backend of choice.

### What are the key takeaways from your post?

Readers will learn:

- How to Setup a Remix project
- How to manage user roles and permissions with Directus
- How to implement user authentication with Directus
- How to automate email notifications (e.g, when a task is assigned to a user)
- How to fetch data with the Remix framework
- How to store task data in Directus CMS

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Are we talking about the UI here? Or just a general task manager with 'lists'?

**Comment by wisdomekpotu** [comment]
Hey @phazonoverload, Not just the UI.

The application will be a product management with lists and categories.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea and the extra context, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
