### ISSUE TITLE
Build a URL Shortener  with React, TypeScript, and Directus

### ISSUE THREAD

**Issue by xKachi** [directus-labs/guest-authoring#156]
### What is your idea?

This article will teach readers how to build a URL shortener with React, Typescript, and Directus.
 

### What are the key takeaways from your post?

In this article, we will create a new project in Directus and define a data model (collection) that we'll use to store information about our shortlinks. Then, we'll create a vite-react project that looks for a slug, queries the associated record in Directus, and redirects the user to the route link.

Key Takeaways:
- Set up Directus with Directus Cloud
- Integrate Directus with React
- Data storage and retrieval with Directus
- Authentication with Directus
- Using Directus Javascript SDK

Post Outline:
- Introduction
- Project Setup with Directus.
- Data Model Setup for the Short Links Collection
- Creating Sample Short Links
- Customizing Roles and Permissions
- Vite(react) Project Setup with TypeScript
- Directus Tokens and Environment Variables
- Installing and Configuring the Directus NPM Package
- Creating the API Endpoint
- Querying Directus and Handling the Redirect
- Conclusion

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $350 for this post and the accompanying repository which you can create in your account and we will fork.

You don't need to show people how to set up a Directus project - just the collections and roles & permissions. Focus on what makes this project special, not boilerplate.

This post will be included as part of our July content schedule. The first draft is due on June 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄
