### ISSUE TITLE
Build a Job Listing Application with Directus and React 

### ISSUE THREAD

**Issue by CodeLeom** [directus-labs/guest-authoring#157]
### What is your idea?

In this article, I'll explain how developers can build a job listing web application with Directus and React.

Features of the application include:

- Listing available jobs on the Landing page
- Using Directus for managing the job listings and users (applicant and job owners)
- Payment options for featured job listings (job owners)
- Search feature to search available jobs
- Applicant job submission/follow link to apply

### What are the key takeaways from your post?

Key takeaways from the article include:

readers will learn how to 
1. use filter parameters in Directus
2. implement relational models in Directus
3. search functionality in the Frontend side

At the end of the article, readers will know how they can develop a job application web app with Directus powering the backend

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We already have this post with Next.js on our blog
