### ISSUE TITLE
Build a project management system with Directus and Angular

### ISSUE THREAD

**Issue by davidmbochi** [directus-labs/guest-authoring#158]
### What is your idea?

In this tutorial, the reader will learn how to develop a project management system leveraging Directus and Angular.

The key features include:

- Allow users to sign up and sign in.
- Enable users to create projects, set project goals, and deadlines, and assign team members.
- Implement a task-tracking system where users can, create, assign, prioritize, and schedule tasks within projects.
- Allow users to track the progress of projects and tasks through visual indicators, timelines, or progress bars.
- Enable users to securely upload, store, and share project-related files and documents.

### What are the key takeaways from your post?

The key takeaways include:

- Understanding how to leverage Directus for user management
- Utilizing Directus collections for project management 
- Understanding task management
- Readers will learn how to visualize project progress
- Implementing file management capabilities

### What type of post is this?

Full Project Build with Directus

### Country of residence

Kenya

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
