### ISSUE TITLE
Getting started with directus and fastapi

### ISSUE THREAD

**Issue by mizzleinetimi** [directus-labs/guest-authoring#160]
### What is your idea?

this tutorial will show developers how to integrate fastapi with directus by building a blog application

### What are the key takeaways from your post?

Readers will learn:

How to set up a FastAPI project to fetch data from Directus.
How to create data collections in a Directus project.
How to set up Directus as a backend using a REST API.
How to build a dynamic web application by integrating FastAPI with Directus.
Potential next steps to enhance the FastAPI and Directus integration.

### What type of post is this?

Other

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.

Right now, we're focusing less on getting started posts and more on project-based tutorials
