### ISSUE TITLE
Build a Customer Review APP with Directus and Next.js

### ISSUE THREAD

**Issue by uma-victor1** [directus-labs/guest-authoring#161]
### What is your idea?

Readers of this tutorial will gain a good understanding of how to put to use the capabilities of Directus as a headless CMS and Next.js as a React framework to create a functional, responsive customer review application. The article will guide readers through every step of the process, from setting up their development environment and building a backend with Directus to implementing the CMS and frontend functionalities. 

### What are the key takeaways from your post?

- Introduction to Directus and Next.js
- Setting up the development environment
- Designing the database schema in Directus
- Building the backend with Directus
- Developing the frontend with Next.js
- Integrating user reviews functionality
- Conclusion

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Can you please provide some more context about the functionality?

**Comment by uma-victor1** [comment]
@phazonoverload I'm going with a [trustpilot](https://www.trustpilot.com/) kinda functionality with this app. 

Here are the functionalities:
- Auth with Directus
- create organization
- Review Submission Form
- Data Validation
- store reviews

**Comment by phazonoverload** [comment]
Got it, thanks. Unfortunately, we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
