### ISSUE TITLE
Creating a Server-Side Rendered App with Go, Gin, and Directus

### ISSUE THREAD

**Issue by Claradev32** [directus-labs/guest-authoring#163]
### What is your idea?

Creating a server-side rendered app by building a backend with Go's Gin framework that fetches data from the Directus headless CMS and renders HTML templates on the server. 

### What are the key takeaways from your post?

- Introduction
  - Brief overview of server-side rendering (SSR) and its benefits
  - Introduction to Go, Gin, and Directus
- Installing Go and Gin
- Creating a new Go project
- Using Global Metadata and Settings
- Passing data from handlers to templates
- Creating Dynamic Pages With Directus
- Rendering Views with Go Templates
- Conclusion

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We mostly focus on JavaScript content at this time - we have enough non-JS guides at the moment. Please feel free to submit additional ideas in future.
