### ISSUE TITLE
Implementing Authentication in React-Native with Directus Flow

### ISSUE THREAD

**Issue by Claradev32** [directus-labs/guest-authoring#165]
### What is your idea?

This guide will give you a hands-on approach to handling user authentication and authorization with Directus and React-Native. It will help mobile developers to learn how to implement user authentication and authorization with Directus.

### What are the key takeaways from your post?

This guide will cover:
- Creating a new project
- Using Global Metadata and Settings
- Creating a new React Native project
- Installing required dependencies (@directus/sdk, axios)
- Initializing Directus SDK
- Configuring Auth Provider (Email, OAuth2 (Google, GitHub))
- Creating a function for user login
- Storing access token
- Secure API Requests
- Creating a function for user logout
- Creating a function to refresh tokens
- Building the App UI

### What type of post is this?

Extension-Building Guide

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
