### ISSUE TITLE
Building a Photo Gallery with Django and Directus

### ISSUE THREAD

**Issue by mizzleinetimi** [directus-labs/guest-authoring#166]
### What is your idea?

the goal is to create a platform where users can upload and manage their photos, organize them into albums, and share their work with others. The application will feature user authentication, photo and album management, content display, and basic sharing and commenting capabilities. 

### What are the key takeaways from your post?

we will be combining Django's robust backend capabilities with Directus's headless CMS for content management to create a seamless and efficient solution.The main focus is on integrating a traditional web framework like Django with a modern headless CMS like Directus. Readers will learn how to combine the strengths of these two technologies to build a robust content-driven application.

### What type of post is this?

Full Project Build with Directus

### Country of residence

nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We mostly focus on JavaScript content at this time - we have enough non-JS guides at the moment. Please feel free to submit additional ideas in future.
