### ISSUE TITLE
Build A Tic-Tac-Toe Multiplayer Game With Reactjs And Directus Real Time

### ISSUE THREAD

**Issue by psalmuelle** [directus-labs/guest-authoring#168]
### What is your idea?

The idea is to build a tic-tac-toe multiplayer game using Reactjs and Directus. The game allows a user to input their nickname and create a connection to play with other users. The real-time gameplay and storing of data is done using Directus Real Time.

A brief outline of the post:
- Introduction
- Prerequisites
- Installing Reactjs and Directus sdk
- Setting up Directus 
- Creating Game UI
- Creating Game Controls and Adding Logic
- Creating Servers
- Joining and Leaving Rooms
- Building the End game logic

### What are the key takeaways from your post?

This post aims to introduce readers to Directus Realt Time features, and how to use Directus SDK to create apps with real-time features.

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
