### ISSUE TITLE
Building a weather app using Openweather api, directus and React js

### ISSUE THREAD

**Issue by TechMakanaki** [directus-labs/guest-authoring#170]
### What is your idea?

The tutorial is to develop a functional weather app that utilizes the OpenWeather API for weather data, Directus for managing your data, and React.js for building the frontend interface. 

### What are the key takeaways from your post?

1. Set up OpenWeather API
2. Set up Directus
3. Set up React.js
4. Build the backend: Create an API endpoint in Directus that fetches weather data from the OpenWeather API
5. Build the frontend
6. Handle user interactions and Styling
7. Conclusion

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria 

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
