### ISSUE TITLE
Building a newsletter application with directus, Twilio SendGrid and django.

### ISSUE THREAD

**Issue by mizzleinetimi** [directus-labs/guest-authoring#174]
### What is your idea?

This article will guide you through creating a newsletter application by integrating Directus as the headless CMS for managing subscriber data, Twilio SendGrid for email delivery, and Django as the web framework. Directus will serve at the backend for storing and managing subscriber information, while SendGrid will handle the email sending functionality, and Django will tie everything together.

### What are the key takeaways from your post?

You'll start by setting up a Django project, installing Directus, and configuring SendGrid. Next, you'll create a collection in Directus for storing subscriber data and connect Django to the Directus API. The article will cover creating views and templates in Django for handling subscription forms, fetching subscriber data from Directus, and using the SendGrid API to send newsletter emails to subscribers. By combining these three powerful technologies, you'll have an awesome solution for managing newsletter subscribers and delivering email campaigns.

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We mostly focus on JavaScript content at this time - we have enough non-JS guides at the moment. Please feel free to submit additional ideas in future.
