### ISSUE TITLE
Simplifying Django Model's Many-to-many relationship, with Directus, for better data handling

### ISSUE THREAD

**Issue by oriohac** [directus-labs/guest-authoring#176]
### What is your idea?

The idea of this article is to first help the reader understand the many-to-many relationship in Django model, which is always confusing or tedious to implement. Then the reader will be shown how Directus BaaS can help us simplify this many-to-many relationship concept.

### What are the key takeaways from your post?

- Readers will understand integration of Directus in a Django App.
- Readers will also learn how to implement the many-to-many relationship in Django model using a ManyToManyField.
- Furthermore, they will learn how Directus helps to simplify this many-to-many relationship.
- They will also learn how to use Directus as a BaaS.

### What type of post is this?

Tips, Tricks, or Best Practice

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We mostly focus on JavaScript content at this time - we have enough non-JS guides at the moment. Please feel free to submit additional ideas in future.
