### ISSUE TITLE
How to build a real-time chat app with Nextjs, Directus and FCM

### ISSUE THREAD

**Issue by Tammibriggs** [directus-labs/guest-authoring#178]
### What is your idea?

This tutorial aims to demonstrate in detail the step-by-step process of using Directus, Next App Router and Firebase Cloud Messaging to build a chat app which includes some essential features needed in a real-world use case like:

- Push notification
- Authentication
- Real-time messaging
- Message read receipt
- user's online/offline status indicator

To keep the tutorial as concise as possible, I plan to build the user interface of the app outside of the tutorial, host it on GitHub and include the details to clone it in the tutorial.

### What are the key takeaways from your post?

Readers will learn:
- How to get data in real-time with Directus
- How to add push notifications when using Directus
- How to implement user authentication 
- How to build a chat app using Directus and Nextjs

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [x] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [x] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This doesn't make sense for us as we have Realtime functionality built in to Directus, and existing chat-based tutorials.

**Comment by Tammibriggs** [comment]
@phazonoverload Firebase Cloud Messaging is for push notifications. I will be using the Directus SDK for implementing real-time functionalities such as message read receipt, online indicators etc which were not covered in the available tutorial.
