### ISSUE TITLE
Build a Pexels clone using Astro and Directus

### ISSUE THREAD

**Issue by am-miracle** [directus-labs/guest-authoring#179]
### What is your idea?

In this article, we'll walk the user through the steps of building a [Pexels](https://www.pexels.com/) clone, starting with setting up the environment, creating the backend using Directus and the front end using Astro, and adding advanced features such as search functionality and pagination.

### What are the key takeaways from your post?

- Readers will learn how to set up the environment to build a Pexels clone.
- Readers will learn how to use Directus as a CMS to manage content for your application.
- Readers will learn how to create content collections and add content.
- Readers will learn how to set up the frontend environment using Astro and React.
- Readers will learn how to build the frontend components to display content fetched from Directus.
- Readers will learn how to add advanced features like pagination, user download, and search functionality to your application.

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
