### ISSUE TITLE
Building a Chrome extension for note-taking with Directus and Flutter.

### ISSUE THREAD

**Issue by SemajCode** [directus-labs/guest-authoring#181]
### What is your idea?

The idea is to develop a Chrome extension that enables users to take notes efficiently. This extension will utilize Directus, a headless CMS, to store and manage notes, and Flutter for crafting the extension's interface. Users will have the capability to view, modify, and remove their notes directly within the extension's interface.

**Post Outline**
* Introduction
* Setting Up a New Flutter Project
* Setting Up the Directus Backend
* User Interface Development with Flutter
* Storing and Retrieving Notes from Directus
* The Extension Configuration and Building Process
* The Extension Installation and Testing 

### What are the key takeaways from your post?

* Integrate Directus with Flutter
* Data storage and retrieval with Directus
* Chrome Extension Development

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Right now we're focusing on JavaScript/TypeScript content. Please feel free to submit additional ideas in future.
