### ISSUE TITLE
Creating a Code Snippet Manager with Directus and React.js

### ISSUE THREAD

**Issue by Claradev32** [directus-labs/guest-authoring#184]
### What is your idea?

In this tutorial, the reader will learn how to develop a code snippet manager application using Directus as the backend and Vue.js as the frontend framework, implementing features like code highlighting, tagging, searching, sharing snippets, and snippet storage using Directus. 

### What are the key takeaways from your post?

- Setting up Directus instance 
- Configuring Directus data models for code snippets
- Initializing the Vue.js project
- Creating components for displaying code snippets
- Implementing code highlighting and syntax formatting
- Fetching code snippets data from Directus
- Creating, updating, and deleting code snippets
- Search and filter functionality
- Copying code snippets to clipboard
- Allowing users to comment on code snippets
- Implementing real-time updates with Directus
- Sharing and exporting code snippets

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We're not going to accept this, but I want to provide some feedback so future submissions have a higher chance of being accepted. 

Firstly, this is a lot. I don't see how, based on the topic, why Realtime or commenting is needed, for example. I'd rather have smaller scoped, more sensible, projects. 

The other part of this is that there's nothing really new here - this could be a blog post. The only thing that makes this code snippet specific is frontend-rendering, which is cool but isn't Directus-related.
