### ISSUE TITLE
Developing a Documentation Portal with Directus and Angular

### ISSUE THREAD

**Issue by preshenv** [directus-labs/guest-authoring#185]
### What is your idea?

This tutorial will cover how to developing a community platform for developers to share knowledge, ask questions, and collaborate and how to integrate content management, and moderation.

### What are the key takeaways from your post?

- Installing Angular CLI and required dependencies
- Setting up Directus Loud (local or cloud-hosted)
- Configuring Directus ata models for documentation content
- Initializing the Angular project
- Creating components for displaying documentation content
- Implementing code highlighting and syntax formatting
- Fetching documentation data from Directus
- Handling content updates and versioning
- Defining Angular routes for different content sections
- Creating a responsive and accessible navigation menu
- Implementing search functionality
- Rendering Markdown content with Angular
- Handling code examples and interactive demos
- Allowing users to comment on documentation pages
 - Implementing upvoting and rating systems

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
