### ISSUE TITLE
Building a Job Board Platform with Directus and SolidStart.js

### ISSUE THREAD

**Issue by preshenv** [directus-labs/guest-authoring#186]
### What is your idea?

This tutorial will expose the readers to the SolidStart, the Solid.js framework. They will learn how the job sites they use is built. They will learn how the process will be simplified using the Directus CMS.

### What are the key takeaways from your post?

- Installing Node.js and SolidStart.js
- Setting up Directus instance
- Configuring Directus data models for job listings, employers, and applicants
- Creating relationships in Directus
- Initializing the SolidStart.js project
- Creating components for displaying job listings
- Implementing search and filtering functionality
- Fetching job listings data from Directus
- Creating, updating, and deleting job listings
- Implementing job application functionality
- Managing applicant profiles and resumes

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This is good, but I want you to minimize the first few topics to get to initializing and setting up the SolidStart project as quickly as possible. 

Based on the agreed scope we can pay $500 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our July content schedule. The first draft is due on July 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by preshenv** [comment]
Hi @phazonoverload,
I can work with your recommendations and happy to commit to the deadline.

Thanks

**Comment by preshenv** [comment]
Hi @BB-Loft 
I have submitted a PR for this draft.
