### ISSUE TITLE
Build a smart note taking app with Directus, Next.js and OpenAI

### ISSUE THREAD

**Issue by gitChimp88** [directus-labs/guest-authoring#190]
### What is your idea?

The idea is to create a note taking app which uses AI to summarise and give suggestions to your notes to help iterate on ideas, ultimately the point is to show how to build something interesting using Directus and other cutting edge technologies.

## Features of the Application Include:
- Creating and Editing Notes: Users can create, edit, and delete notes with a simple and intuitive interface.
- AI-Powered Summarisation: Automatically generate summaries and suggestions of notes using AI.
- Organsing Notes: Automatically categorise and tag notes based on content.
- Search Feature: Search notes using keywords and filters.
- User Authentication: Secure login and registration for users.

### What are the key takeaways from your post?

- Learning how to integrate AI for text summarisation and suggestions.
- Implementing a robust note-taking interface with Next.js.
- Using Directus to manage user data and notes.
- Setting up search functionality to quickly find and filter notes.
- Understanding how to implement user authentication.

### Country of residence

Spain

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
