### ISSUE TITLE
Build Your Freelancer's CRM Application with Directus

### ISSUE THREAD

**Issue by psalmuelle** [directus-labs/guest-authoring#191]
### What is your idea?

The idea is to create a customer relationship management app just with Directus. This article will guide freelancers on how to set up a CRM for their app, adding functionalities that suit their tastes. Some of the features that will be discussed in this article include:
- Client Management; client database, adding clients to CRM to follow up projects, client interaction history and grouping clients into categories.
- Project Management: project tracking, task management and time tracking
- Financial Management: Invoicing, expense tracking, creating and sending quotes to customers
- Email and Slack integration.
- Scheduling and automation. 
- Other features that can be added to the CRM.

### What are the key takeaways from your post?

This article aims to introduce freelance developers, writers and non-developers alike, the possibilities of Directus. How they can use directus to scale their freelance business and enhance customer's satisfaction.customer

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
