### ISSUE TITLE
  Creating a SQL headless CMS with Directus

### ISSUE THREAD

**Issue by leviOnNet** [directus-labs/guest-authoring#193]
### What is your idea?

Talk about how Directus allows developers to wrap any database of choice with an API later, turning the database into a headless CMS and adds the database structure for User models with roles and permissions, dashboards, file directory, content models and many more.  

In this case, i will using SQL.

### What are the key takeaways from your post?

What is Directus. Installing and using Directus offline. Integrating Directus with SQL database. Using Directus backend dashboard to make system changes. Creating a Headless CMS with Directus. Code example for the Headless CMS web application.

### Country of residence

South Africa

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.

**Comment by leviOnNet** [comment]
Hello,

If you don't mind me asking. Which type of topics are you looking for? And
why not this one?


Regards,
Levis Masonde
