### ISSUE TITLE
Build a Content Approval System for Technical Writing programs in Directus

### ISSUE THREAD

**Issue by techbabe23** [directus-labs/guest-authoring#195]
### What is your idea?

The first thing is that my idea is a Content Approval System that allows users to simplify the content approval process.
Outline
1. The Introduction will include explaining content approval process problems, as well as how they can be solved through implementing custom interfaces.
2. Explaining the importance of user-friendly content approval systems and their impact on collaboration.
3. Planning the interface & how to set up for the project
4. Designing the interface
5. Building reusable components for long term
6. Conclusion 

### What are the key takeaways from your post?

At the end of the post the readers will be able to
1. Understand the benefits of custom-made content approval systems
2.  Understand data manipulation skills
3. Learn how to build reusable components
4. Learn how to build a Directus extension with a frontend interface

### Country of residence

South Africa

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This feels quite meta given we're here managing a technical writing program. 

Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. We have existing content on authoring and approval workflows. Please feel free to submit additional ideas in future.

**Comment by techbabe23** [comment]
Thank you, I submitted a new one.
