### ISSUE TITLE
Building an Inventory Management System with Next.js and Directus

### ISSUE THREAD

**Issue by Victory-ET** [directus-labs/guest-authoring#196]
### What is your idea?

In this article, I will guide readers through the process of creating an inventory management system using Next.js and Directus. The system will allow users to track and manage their inventory, including adding new items, updating stock levels, and generating reports. Directus will act as the back-end to store inventory data, while Next.js will handle the front-end interface for interacting with this data. This approach provides a streamlined and efficient way to manage inventory, offering real-time updates and a user-friendly interface.

### What are the key takeaways from your post?

- Inventory tracking using Next.js to build a user-friendly interface to track inventory items and allow users to add, edit, and delete inventory items stored in Directus.
- Real-time data synchronization, access, and interfacing between the front end and Directus to ensure inventory levels are always up to date.
- Providing features for generating reports and analyzing inventory data to make informed business decisions.
- App scalability, customization, and flexibility features by leveraging Directus for content orchestration.

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
- [X] You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
I don't see the value that a Next.js frontend has here, when you could feasibly do all of this inside of the Data Studio. Would you be open for making this a tutorial around data modeling and usage entirely inside of the Data Studio?

**Comment by Victory-ET** [comment]
Thank you for the review @phazonoverload. Yes, I can make the article centered around creating an inventory management system using the Data Studio instead.

**Comment by Victory-ET** [comment]
Hi @BB-Loft Thanks for the offer. It's perfectly fine by me. I'll get started on the draft and deliver on the agreed date.

**Comment by Victory-ET** [comment]
Hi @BB-Loft I have submitted a PR
