### ISSUE TITLE
Build a Note-Taking Website with Qwik, Directus, Tailwind CSS, and TypeScript

### ISSUE THREAD

**Issue by tonie-ng** [directus-labs/guest-authoring#287]
### Inactive

- [X] You understand that if you submit this form, your issue will be closed without review.

**Comment by tonie-ng** [comment]
Hello @phazonoverload, I spent the last couple of days working on a prototype application to showcase this. Coming now and seeing that the program is closed is a little bit disheartening. Is there any way I can still get in? I already spent the bulk of my time drafting something. Thank you.
Here is a link to the application: https://github.com/tonie-ng/qwik-journal

**Comment by phazonoverload** [comment]
I understand but our process explicitly stated `Please wait for us to approve it before you start.` This specific topic likely would not have been accepted based on our priorities before we closed the proposal form. I understand this likely isn't the response you wanted, and apologies for any bad feeling it has caused.

**Comment by tonie-ng** [comment]
Alright, I understand your position. Thank you.
