### ISSUE TITLE
How to Run Directus to Google Cloud

### ISSUE THREAD

**Issue by codejagaban** [directus-labs/guest-authoring#45]
### What is your idea?

In this article, I'll provide a comprehensive guide on how to run Directus on the Google Cloud Platform (GCP). I'll also cover setting up a GCP account, configuring Google Cloud SQL and Storage for Directus, and deploying Directus on a Google Cloud Compute Engine.

### What are the key takeaways from your post?

Readers will learn the following:

- How to set up a GCP account
- How to configure Google Cloud SQL
- How to configure Google Cloud Storage for Directus
- Setting up a  Compute Engine instance

### What type of post is this?

Self-Hosting Guide

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Let's finish up some other posts you've pitched before picking up any others.

**Comment by codejagaban** [comment]
That works great with me @phazonoverload  thanks
