### ISSUE TITLE
Using Directus with Django

### ISSUE THREAD

**Issue by mizzleinetimi** [directus-labs/guest-authoring#53]
### What is your idea?

this article will show developers how to integrate directus by creating a blog Api the will be consumed and rendered with django.

### What are the key takeaways from your post?

1. Setting Up a Django Project: we'll start by creating a new Django project, which will serve as the base for the Blog API. 

2. Creating a Django Model for Blog Posts: Learn how to define a Django model specifically for blog posts.

3. Consuming the Directus API in Django: we'll discover how to fetch blog post data from Directus using Django. We'll guide you through making HTTP requests to the Directus API to retrieve blog content.

4. Displaying Blog Posts with Django Templates: This section will teach how to use Django's templating engine to render blog posts on the webpage. 

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
We can pay $250 for this post - it should follow the same format as our other 'Getting Started with Directus and X' posts on our dev blog. If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by mizzleinetimi** [comment]
The deadline is fine, thanks!
