### ISSUE TITLE
Auth with Directus and iOS

### ISSUE THREAD

**Issue by HarshpalBhirth** [directus-labs/guest-authoring#55]
### What is your idea?

Adding Authentication and being able to create a new item using a form

### What are the key takeaways from your post?

- Authentication: create account, login, logout
- Creating a new item using a form 

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

United Kingdom 

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
The scope should be slightly increased:

- Register, login, logout
- See all posts from all users
- Create post
- User Profile page
  - See just posts from your user
  - Edit/delete posts from your user

If this sounds good, we can pay $350 for this post. If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄

**Comment by phazonoverload** [comment]
Hey @HarshpalBhirth I've extended the first draft deadline to March 10
