### ISSUE TITLE
Building and Deploying a Personal Travel Journal with Vue.js, Directus, and Kubernetes

### ISSUE THREAD

**Issue by mercybassey** [directus-labs/guest-authoring#56]
### What is your idea?

In this project, I aim to build and deploy a personalized travel journal using Vue.js, Directus, and Kubernetes. The application will enable users to create, edit, and visually document their travel experiences through entries that can include titles, descriptions, and attached photos. Leveraging Directus as the headless CMS, I'll manage data storage, and retrieval via its API. The Vue.js frontend will ensure an intuitive and visually appealing user interface, while Dockerization facilitates consistent deployment. Kubernetes deployment further ensures scalability and efficient management in a production environment, allowing users to explore their travel history dynamically through interactive maps. 

### What are the key takeaways from your post?

The key takeaways from my proposed idea are as follows:
- The reader will gain proficiency in full-stack development by building a Vue.js frontend, integrating it with the Directus, and deploying the application to Kubernetes.
- They'll also Acquire skills in incorporating interactive maps into Vue applications, so users can dynamically explore their travel history based on geocoded entries.
- Finally, they'll understand Kubernetes basics for container orchestration and writing manifests for deployment and they'll see how to deploy this proposed idea to Kubernetes.

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Like this idea - we haven't had enough project-based tutorials on the dev blog yet. A few thoughts: 

1. Would this application handle auth as well? 
2. I'm personally not too interested in the Dockerization or deployment with K8S for this post as it widens the scope too much for me. Happy for the build to be 'local' and deployment is down to the reader. 

Thoughts?

**Comment by mercybassey** [comment]
Then I'll omit the dockerization and K8s part. Also, based on the original setup, I didn't want to include auth. I could replace the dockerization and K8s part with it then.

**Comment by phazonoverload** [comment]
Yeah that sounds good to me. Just to clarify, the scope is now: 

- Users can create accounts/login (no need to handle SSO, forgot password, etc)
- Create and edit entries incl images

We can pay $500 for this post and accompanying project repo (the repo can live in your account, and we'll fork it to this repo). 

If interested, let me know when you think you could have a first draft ready. It isn't a hard deadline, but it gives me an idea of when this might be added into our content schedule. 

The process is detailed in the README of this repo 😄
