### ISSUE TITLE
Build an hotel booking and reservations system with Directus, Next.js and Stripe

### ISSUE THREAD

**Issue by codejagaban** [directus-labs/guest-authoring#65]
### What is your idea?

In this article, we will build a hotel management system using Next with booking and reservation features.js as the Frontend of the application and Directus as the backend.

Features of the application include:

- Listing available rooms on the Frontend
- Using Directus for managing the data
- Receiving payment with Stripe
- After payment confirmation, perform a request to Directus to block the availability of the paid room

### What are the key takeaways from your post?

At the end of the article, readers will have an overview of how they can easily set up a booking and reservations system with Directus and receiver payments in their applications

### What type of post is this?

Full Project Build with Directus

### Country of residence

United Kingdom

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting an idea for our guest blog.
            
We work through new ideas every few weeks as we put together our content schedule. This means you may not get an immediate response as to whether your idea has been accepted, or any follow-up questions we have to clarify your idea. 

If your idea is accepted, we will provide a deadline for first draft and how much we can pay you for the post. You will have a few days to confirm whether you are still able and willing to write the post. 

If you have any questions in the meantime, feel free to add a comment to this issue.

**Comment by phazonoverload** [comment]
This is good. From the outline I want you to spend the least time on the frontend - minimal/no styling, no styling-based additional libraries. The availability listing, payment, and availability blocking is a good amount for the project. Also don't spend too long showing readers how to spin up a new project - you can include that in the prerequisites. 

Based on the agreed scope we can pay $500 for this post and the accompanying frontend repository which you can create in your account and we will fork.

This post will be included as part of our April content schedule. The first draft is due on March 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days.

The process is detailed in the README of this repo 😄

**Comment by phazonoverload** [comment]
Let me know if this is of interest by Wednesday please 😄

**Comment by codejagaban** [comment]
Hi @phazonoverload  yes sure this works fine with me
