### ISSUE TITLE
Build a Support Ticket Application for Users with Directus

### ISSUE THREAD

**Issue by CodeLeom** [directus-labs/guest-authoring#84]
### What is your idea?

This article will help frontend developers know how to use Directus to build an application. In this article, I will be building a support ticket website that visitors can use to submit their queries or issue of a particular product.

Javascript will be used as the Frontend of the application and Directus as the backend.

Features of the application include:
- SignUp/Login (Authentication)
- Submit Ticket, Add Notes to opened Ticket
- Using Directus for managing the data
- After ticket is submitted, The admin will receive an email Notification

### What are the key takeaways from your post?

At the end of the article, readers will have an overview of how they can easily set up a support ticket application with Directus.

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Genuine question - why couldn't this happen completely within Directus? With an admin 'inviting' customers with a specific role, etc. Would you be open to just doing this without a separate application and entirely within the Directus Data Studio?

**Comment by CodeLeom** [comment]
@phazonoverload This can happen completely within Directus and I am open to doing this without any seperate application. I will build the project using the Directus Data Studio and write an article about it

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $250 for this post.

This post will be included as part of our April content schedule. The first draft is due on March 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by CodeLeom** [comment]
I am interested to take this forward, and I will commit to the deadline.

Regards
