### ISSUE TITLE
Building a Storehub with Golang and Directus

### ISSUE THREAD

**Issue by Claradev32** [directus-labs/guest-authoring#85]
### What is your idea?

This article will show developers how to integrate Directus with Golang by creating a Storehup web application.

### What are the key takeaways from your post?

This article will help developers know how to use Directus to build a store hub application. In this article, I will be building a Storehub where users will display and sell their products. I will use Directus to save products and use SSR and template handling in Golang to display the products.
Outlines of the application include:
- Setting Up a Golang Project
- Creating a Model for Users and Products
- Creating Collections in Directus
- Creating Data Relationship
- Consuming the Directus API in Golang
- Implementing SSR and templating to display products

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
