### ISSUE TITLE
Build a Multilingual News app using Sveltekit with Directus i18n API

### ISSUE THREAD

**Issue by icode247** [directus-labs/guest-authoring#89]
### What is your idea?

In this tutorial, the reader will learn how to develop a multilingual news application using SvelteKit for the front end and leveraging Directus's i18n (internationalization) API for content management across different languages.

### What are the key takeaways from your post?

The key takeaways are as follows:
- The Concept of i18n
- Understanding Directus i18n API
- Installing SvelteKit and setting up a new project.
- Designing the Data Model in Directus 
   - Setting up collections for news articles with multilingual support.
   - Creating relationships and defining fields in Directus.
- Building the News App Frontend with SvelteKit
- Integrating Directus i18n with SvelteKit
- Implementing News Article Pages
- Adding Multilingual Navigation and Search
  - Creating a language switcher.
  - Implementing search functionality with language support.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Very nice idea. 

Based on the agreed scope we can pay $350 for this post and the accompanying repository which you can create in your account and we will fork.

This post will be included as part of our May content schedule. The first draft is due on April 2 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by icode247** [comment]
> Very nice idea.
> 
> Based on the agreed scope we can pay $350 for this post and the accompanying repository which you can create in your account and we will fork.
> 
> This post will be included as part of our May content schedule. The first draft is due on April 2 so we have time to properly review it and you have time to respond.
> 
> If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.
> 
> The process is detailed in the README of this repo 😄

**Comment by icode247** [comment]
Apologies, my keyboard was frozen for a moment. The post schedules work for me and I tailor the content to your suggestion.

**Comment by phazonoverload** [comment]
Hey @icode247 any update on this?

**Comment by icode247** [comment]
Sure @phazonoverload 
I have been working on it. Expect a PR on the 11th.
