### ISSUE TITLE
How to Integrate Directus with Angular

### ISSUE THREAD

**Issue by davidmbochi** [directus-labs/guest-authoring#91]
### What is your idea?

Angular is one of the most used frontend development frameworks. As a result, providing a detailed article on this topic will be very helpful to those readers implementing their solution using Angular. In this tutorial, the reader will create an art application by leveraging Directus to create art API with some custom images for the gallery. In addition, each image for the Art will contain some descriptive information.

### What are the key takeaways from your post?

- How to create an Angular project
- How to create a DTO for the art API using Angular
- How to consume the art API using Angular
- How to display the art gallery using Angular

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Kenya

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This has to follow the standard format for our framework getting started guides: 

- Initialize project
- Create a helper/lib/plugin (unsure of Angular-specific terminology) for Directus SDK
- Globals
- Dynamic Pages
- Blog listing
- Blog single
- Nav

Here's an example: https://docs.directus.io/guides/headless-cms/build-static-website/nuxt-3

Based on this, we can pay $250 for this post.

This post will be included as part of our April content schedule. The first draft is due on March 1 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by davidmbochi** [comment]
Hi @phazonoverload. Am working to have the first draft ready in due time.
