### ISSUE TITLE
Building a Dynamic Portfolio Website with Directus and Vue.js

### ISSUE THREAD

**Issue by marvelken** [directus-labs/guest-authoring#95]
### What is your idea?

This topic explores how to leverage Directus as a backend to manage portfolios, blog posts, and testimonials while using Vue.js for the frontend to create a responsive and interactive personal or agency portfolio website. It focuses on utilizing Vue.js's reactivity and component system alongside Directus's RESTful API or GraphQL for real-time content updates without page reloads.

### What are the key takeaways from your post?

Utilization of Directus for Content Management: Directus serves as the backend system, enabling easy management of various types of content such as portfolios, blog posts, and testimonials. 

Reactive Frontend Development with Vue.js: Vue.js is utilized for the frontend to create a responsive and interactive user experience. Its reactivity and component system allow for building dynamic interfaces that update in real-time, offering a seamless experience for users as they navigate through the portfolio website. 

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
