### ISSUE TITLE
Developing an Interactive Educational Platform with Directus and React

### ISSUE THREAD

**Issue by marvelken** [directus-labs/guest-authoring#96]
### What is your idea?

Developing an Interactive Educational Platform with Directus and React: This idea delves into creating an educational platform where course materials, quizzes, and student progress can be managed through Directus, while the interactive user interface is built using React. It covers creating dynamic, user-specific content that updates based on student progress and integrating multimedia content management for a seamless learning experience.

### What are the key takeaways from your post?

Comprehensive Content Management with Directus: Directus is utilized as the backend content management system (CMS) to manage diverse educational materials, including course content, quizzes, and tracking student progress. Its headless nature allows for the centralized management of educational content, which can be dynamically served to the React frontend through its API. This setup facilitates the easy update and expansion of course materials without affecting the frontend structure.

### What type of post is this?

Getting Started With Directus and {Language/Framework/Environment}

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This is a big project so I want to see if we can reduce it in scope. It seems to be all about a learning management platform - I wonder if we focus on the data modeling and permissions, and build a super super minimal (if any) frontend. Thoughts?

**Comment by marvelken** [comment]
That would be ok by me, what's the next step?

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $250 for this post. Just to be clear, the frontend should be as minimal as possible, no styling, etc. This is an exercise in data modeling and permissions. 

This post will be included as part of our May content schedule. The first draft is due on April 2 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by phazonoverload** [comment]
PS. Paying Nigerian bank accounts has continued to be a challenge as a non-Nigerian company. Having a US IBAN or a PayPal account seems to work best. Happy to discuss over email - [kevin@directus.io](mailto:kevin@directus.io)

**Comment by marvelken** [comment]
Hi Kevin, I am interested, and the draft will be ready on or before April 2nd, I just sent an email regarding the bank issue.

**Comment by marvelken** [comment]
@phazonoverload, Hi Sir, Where would I submit this article, I emailed you previously and got no response.

**Comment by phazonoverload** [comment]
@marvelken as mentioned, the README of this repo contains the process - I'd like it as a PR please. I just saw your email. I can extend to April 15 - will that work as a hard deadline for a first draft?

**Comment by marvelken** [comment]
@phazonoverload Hi Kevin, I have submitted the article please take a look, and can you help take off the billing on my card? If they try billing me again, the card could be frozen for insufficient balance. my account: marvelken2000@gmail.com

**Comment by phazonoverload** [comment]
You'll need to get in touch with support@directus.io - this repo is for the guest author program and is managed by a different team.
